// Generated by CoffeeScript 1.4.0
(function() {
  var mongoose;

  mongoose = require("mongoose");

  /*
  Paranoid Delete:
  Creates a shadow collection xxx-deleted that contains deleted versions.
  */


  exports.deleteParanoid = function(schema, options) {
    if (!options) {
      options = {};
    }
    return schema.add({
      deletedAt: {
        type: Date,
        "default": null
      },
      isDeleted: {
        type: Boolean,
        "default": false
      }
    });
  };

}).call(this);
